# Generated by Django 4.1.1 on 2022-09-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(max_length=400)),
                ('menu', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Store',
            },
        ),
    ]
