# Generated by Django 4.1.1 on 2022-09-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('email', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=120)),
                ('place', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('password', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Userdata',
            },
        ),
    ]
